menu/urls.py
from django.urls import path
from menu.views import child, page1, page2

app_name = "menu"

urlpatterns = [
    path('child/', child, name="child"),
    path('page1/', page1, name="page1"),
    path('page2/', page2, name="page2"),
]

project_site/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
]

menu/models.py
from django.db import models

# Create your models here.

menu/views.py
from django.shortcuts import render



def child(request):
    return render(request, 'menu/child.html')

def page1(request):
    return render(request, 'menu/page1.html')

def page2(request):
    return render(request, 'menu/page2.html')

menu/templates/menu/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Montserrat:wght@700;800;900&display=swar" rel="stylesheet">
    <title>{% block title %}{% endblock %} | Hotels</title>
</head>
<body>
    <header>
        <nav>
            <h2 class="logo">Бронирование <span>отелей</span></h2>
            <div>
                <ul>
                    <li><a href="#">Главная</a></li>
                    <li><a href="#">Контакты</a></li>
                    <li><a href="#">Помощь</a></li>
                </ul>
            </div>
            <button type="button">Подписаться</button>
        </nav>
    </header>
    <section>
        <div class="section-main">
            {% block content %}
            {% endblock %}
        </div>
    </section>
    <footer>
        {% block footer %}{% endblock %}
    </footer>
   </body>
</html>

menu/templates/menu/child.html
{% extends 'menu/base.html' %}

{% block title %}Добро пожаловать{% endblock %}

{% block content %}
  <h1>Добро пожаловать на наш сайт!</h1>
{% endblock %}

{% block footer %}
    <h3>&copy; Все права защищены.</h3>
{% endblock %}

menu/templates/menu/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"> </script>
    <link href="{% static 'css/style_main.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %} | Hotels</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-grey-200">
        <a href="#" class="flex-xl font-semibold">Бронирование отелей</a>
        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-grey-500">Отели</a>
                <a href="#" class="text-lg font-semibold hover:text-grey-500">Акции</a>
                <a href="#" class="text-lg font-semibold hover:text-grey-500">Контакты</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover: bg-teal-700">Dashboard</a>
        </div>
    </nav>
      <div id="page">
          {% include 'menu/sidebar.html' %}
      <div id="content">
          {% block content %}
          {% endblock %}
      </div>
  </div>


    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-500">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab aspernatur atque corporis cupiditate, dolorum earum facilis fugiat fugit illo illum ipsa natus nobis optio porro possimus praesentium repellat unde! Velit?</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-500">Menu</h3>
            <ul class="space-y-2">
                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="#">Отели</a>
                </li>
                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="#">Акции</a>
                </li>
                <li class="text-lg text-teal-500 hover:text-teal-700">
                    <a href="{% url 'menu:page1' %}">Контакты</a>
                </li>
            </ul>
        </div>
    </footer>
</body>
</html>

menu/templates/menu/page1.html
{% extends 'menu/main.html' %}

{% block title %}1 Страница{% endblock %}

{% block sidebar %}
    <h1>Первая страница</h1>
{% endblock %}

{% block content %}
    <h2>Очень подробное описание Первой страницы</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus accusantium blanditiis deserunt, libero modi possimus reiciendis sed sit. Autem dignissimos dolores eaque excepturi harum itaque labore nostrum tenetur ut vitae.</p>
{% endblock %}

{% block footer %}
    <h3>&copy; Все права защищены.</h3>
{% endblock %}

menu/templates/menu/page2.html
{% extends 'menu/main.html' %}

{% block title %}2 Страница{% endblock %}

{% block sidebar %}
    <h1>Первая страница</h1>
{% endblock %}

{% block content %}
    <h2>Очень подробное описание Второй страницы</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab adipisci alias amet architecto, atque expedita labore maiores mollitia non odit sequi sint tempora tempore ut, vel velit veniam voluptatem voluptatum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias commodi cupiditate, eaque enim excepturi fugit ipsa iste mollitia nobis nostrum officia perspiciatis quam reprehenderit saepe sapiente sunt totam, vel voluptatibus.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate delectus deleniti doloremque expedita illo neque, nisi non officia. Aspernatur assumenda debitis illo ipsa labore laborum modi officia, quod tempora ut.</p>
{% endblock %}

{% block footer %}
    <h3>&copy; Все права защищены.</h3>
{% endblock %}

menu/templates/menu/sidebar.html
<div id="sideBar">
    {% block sidebar %}
    {% endblock %}
</div>